spring:
  application:
   name: email_sender
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.3:53332/myhome
    username: stock_admin
    password: sss1234
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.naver.com
    port: 465
    username: singsiuk9315@naver.com
    password: EKXEZUFQNDJD
